name: Create Release Zip

on:
  release:
    types: [created]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          cd plugin
          npm install
          # Remove the problematic tsc package that's not the TypeScript compiler
          npm uninstall tsc || true
          # Verify TypeScript is available and show version
          npx typescript --version || echo "TypeScript not found via npx typescript"
          # Try using the TypeScript compiler directly from node_modules
          node ./node_modules/typescript/bin/tsc || echo "Direct TypeScript call failed"
        continue-on-error: true

      - name: Create repository zip
        run: |
          # Remove .git directory to avoid including git history in zip
          rm -rf .git

          # Create zip of entire repository (including the built files)
          zip -r "Spooder-AlertToaster-${{ github.event.release.tag_name }}.zip" . -x "*.git*"

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Spooder-AlertToaster-${{ github.event.release.tag_name }}.zip
          asset_name: Spooder-AlertToaster-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
